name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy to dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: build
        run: scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: push to repository
        run: 'gcloud builds submit --tag asia-south1-docker.pkg.dev/notely-423017/notely-ar-repo/notely:latest .'

      - name: Deploy to Cloud Run
        run: 'gcloud run deploy notely --image asia-south1-docker.pkg.dev/notely-423017/notely-ar-repo/notely:latest --region asia-south1 --allow-unauthenticated --project notely-423017 --max-instances=4'

